flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
ghc-options:
  pandoc-citeproc:  '-pgmP cpphs -optP--cpp'
  highlighting-kate: '-pgmP cpphs -optP--cpp'
packages:
- '..'
extra-deps:
- 'pandoc-citeproc-0.10.1'
- 'http-client-0.5.0'
- 'http-client-tls-0.3.0'
- 'data-default-instances-base-0.1.0.1'
- 'cmark-0.5.3.1'
- 'aeson-pretty-0.8.1'
- 'texmath-0.8.6.5'
resolver: nightly-2016-07-11
